version: "3.8"

services:
  starter_runner:
    image: fbe-dockerreg.rwu.de/doz-iki/staehle-vls/amr-tb3:latest
    container_name: lane_follow_sim
    privileged: true
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=${TERM}
      - ROS_DOMAIN_ID=42 # replace with botID
      - ROS_LOCALHOST_ONLY=1
      - IKI_GIT=${IKI_WORKSPACE}/ros2_ws
      - ROS_WS=/root
      - TURTLEBOT3_MODEL=burger
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${IKI_WORKSPACE}/ros2_ws:/root
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /usr/share/gazebo/setup.bash &&
        source /root/install/setup.bash &&
        ros2 launch tb3_rwu_arena tb3_sim.launch.py x:=0.82 y:=-1.75 yaw:=0.0 &
        source /opt/ros/humble/setup.bash &&
        source /usr/share/gazebo/setup.bash &&
        source /root/install/setup.bash &&
        echo 'Starting lane following simulation...' &&
        ros2 run autorace_real follow_line_real --ros-args -p line:=white
      "